services:
  api:
    container_name: sporthub_api
    image: sporthub_api
    build:
      context: ./api
      dockerfile: api.Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - api/.env
    depends_on:
      - db
    volumes:
      - ./api/src:/usr/src/app/src
      - ./api/public:/usr/src/app/public
      - ./api/uploads:/usr/src/app/uploads
  db:
    image: postgres
    container_name: sporthub_postgresql
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=meda
      - POSTGRES_PASSWORD=meda
      - POSTGRES_DB=sporthubDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
